language: node_js
node_js:
  - "6.0"
before_script:
  - npm install polymer-cli
  - npm install -g firebase-tools
  - npm install -g bower
  - bower update
  # - bower install --save webcomponents/webcomponentsjs
 
script: polymer build
after_success:
  - firebase --project staging deploy --only hosting --token $FIREBASE_TOKEN