language: node_js
node_js:
  - "4.0"
before_script:
  - npm install -g gulp
  - npm install gulp
  - npm install polymer-cli
  - npm install -g bower
  - npm install css-slam
  - npm install html-minifier
  - npm install uglify-js
  - npm install -g firebase-tools
  - bower update
  - bower install --save webcomponents/webcomponentsjs
 
script: polymer build
after_success:
  - firebase deploy --only hosting --token $FIREBASE_TOKEN